package com.koala.portal.constants;

public class ErrorMessages {

    public static final String BLANK_REQUIRED = "The '%s' field is blank or null and is a required field.";
    public static final String NULL_REQUIRED = "The '%s' field is null and is a required field.";
    public static final String FIELD_AUTO_GENERATED = "The field '%s' is generated by the system and is not allowed to be provided here.";

    public static final String DEMAND_VALID = "Provide a valid value in the '%s' field and try again.";
    public static final String DEMAND_NO_VALUE = "Do not provide a value in the '%s' field and try again.";
}
